apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    tier: {{ .Values.tier }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: {{ .Values.tier }}
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          env:
            - name: NEXT_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: NEXT_ENVIRONMENT
            - name: NEXT_BE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: NEXT_BE_HOST